# Generated by Django 2.2.7 on 2019-11-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='naver_score',
            field=models.FloatField(),
        ),
    ]
