# Generated by Django 2.2.7 on 2019-11-28 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191127_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
